//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPConsoleClient.opservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="opservice.IOrder")]
    public interface IOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getCustomer", ReplyAction="http://tempuri.org/IOrder/getCustomerResponse")]
        string getCustomer(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getCustomer", ReplyAction="http://tempuri.org/IOrder/getCustomerResponse")]
        System.Threading.Tasks.Task<string> getCustomerAsync(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/Purchase", ReplyAction="http://tempuri.org/IOrder/PurchaseResponse")]
        int Purchase(string cid, string[] od);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/Purchase", ReplyAction="http://tempuri.org/IOrder/PurchaseResponse")]
        System.Threading.Tasks.Task<int> PurchaseAsync(string cid, string[] od);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getOrderDetails", ReplyAction="http://tempuri.org/IOrder/getOrderDetailsResponse")]
        string[] getOrderDetails(string oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getOrderDetails", ReplyAction="http://tempuri.org/IOrder/getOrderDetailsResponse")]
        System.Threading.Tasks.Task<string[]> getOrderDetailsAsync(string oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getCustomerOrders", ReplyAction="http://tempuri.org/IOrder/getCustomerOrdersResponse")]
        string[] getCustomerOrders(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getCustomerOrders", ReplyAction="http://tempuri.org/IOrder/getCustomerOrdersResponse")]
        System.Threading.Tasks.Task<string[]> getCustomerOrdersAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getProductIds", ReplyAction="http://tempuri.org/IOrder/getProductIdsResponse")]
        string[] getProductIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getProductIds", ReplyAction="http://tempuri.org/IOrder/getProductIdsResponse")]
        System.Threading.Tasks.Task<string[]> getProductIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getProductDetail", ReplyAction="http://tempuri.org/IOrder/getProductDetailResponse")]
        string getProductDetail(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/getProductDetail", ReplyAction="http://tempuri.org/IOrder/getProductDetailResponse")]
        System.Threading.Tasks.Task<string> getProductDetailAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderChannel : OPConsoleClient.opservice.IOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderClient : System.ServiceModel.ClientBase<OPConsoleClient.opservice.IOrder>, OPConsoleClient.opservice.IOrder {
        
        public OrderClient() {
        }
        
        public OrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCustomer(string cid) {
            return base.Channel.getCustomer(cid);
        }
        
        public System.Threading.Tasks.Task<string> getCustomerAsync(string cid) {
            return base.Channel.getCustomerAsync(cid);
        }
        
        public int Purchase(string cid, string[] od) {
            return base.Channel.Purchase(cid, od);
        }
        
        public System.Threading.Tasks.Task<int> PurchaseAsync(string cid, string[] od) {
            return base.Channel.PurchaseAsync(cid, od);
        }
        
        public string[] getOrderDetails(string oid) {
            return base.Channel.getOrderDetails(oid);
        }
        
        public System.Threading.Tasks.Task<string[]> getOrderDetailsAsync(string oid) {
            return base.Channel.getOrderDetailsAsync(oid);
        }
        
        public string[] getCustomerOrders(string id) {
            return base.Channel.getCustomerOrders(id);
        }
        
        public System.Threading.Tasks.Task<string[]> getCustomerOrdersAsync(string id) {
            return base.Channel.getCustomerOrdersAsync(id);
        }
        
        public string[] getProductIds() {
            return base.Channel.getProductIds();
        }
        
        public System.Threading.Tasks.Task<string[]> getProductIdsAsync() {
            return base.Channel.getProductIdsAsync();
        }
        
        public string getProductDetail(string id) {
            return base.Channel.getProductDetail(id);
        }
        
        public System.Threading.Tasks.Task<string> getProductDetailAsync(string id) {
            return base.Channel.getProductDetailAsync(id);
        }
    }
}
