//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.jwsopservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jwsorderprocessing/", ConfigurationName="jwsopservice.OrderProcessingService")]
    public interface OrderProcessingService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getOrderDetailsRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getOrderDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestClient.jwsopservice.getOrderDetailsResponse getOrderDetails(TestClient.jwsopservice.getOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getOrderDetailsRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getOrderDetailsResponse")]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getOrderDetailsResponse> getOrderDetailsAsync(TestClient.jwsopservice.getOrderDetailsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/PurchaseRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/PurchaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestClient.jwsopservice.PurchaseResponse Purchase(TestClient.jwsopservice.PurchaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/PurchaseRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/PurchaseResponse")]
        System.Threading.Tasks.Task<TestClient.jwsopservice.PurchaseResponse> PurchaseAsync(TestClient.jwsopservice.PurchaseRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getCustomerRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getCustomerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestClient.jwsopservice.getCustomerResponse getCustomer(TestClient.jwsopservice.getCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getCustomerRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getCustomerResponse")]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getCustomerResponse> getCustomerAsync(TestClient.jwsopservice.getCustomerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getProductDetailRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getProductDetailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestClient.jwsopservice.getProductDetailResponse getProductDetail(TestClient.jwsopservice.getProductDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getProductDetailRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getProductDetailResponse")]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getProductDetailResponse> getProductDetailAsync(TestClient.jwsopservice.getProductDetailRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getProductIdsRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getProductIdsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestClient.jwsopservice.getProductIdsResponse getProductIds(TestClient.jwsopservice.getProductIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getProductIdsRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getProductIdsResponse")]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getProductIdsResponse> getProductIdsAsync(TestClient.jwsopservice.getProductIdsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getCustomerOrdersRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getCustomerOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestClient.jwsopservice.getCustomerOrdersResponse getCustomerOrders(TestClient.jwsopservice.getCustomerOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jwsorderprocessing/OrderProcessingService/getCustomerOrdersRequest", ReplyAction="http://jwsorderprocessing/OrderProcessingService/getCustomerOrdersResponse")]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getCustomerOrdersResponse> getCustomerOrdersAsync(TestClient.jwsopservice.getCustomerOrdersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrderDetails", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getOrderDetailsRequest() {
        }
        
        public getOrderDetailsRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrderDetailsResponse", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getOrderDetailsResponse() {
        }
        
        public getOrderDetailsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Purchase", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class PurchaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg1;
        
        public PurchaseRequest() {
        }
        
        public PurchaseRequest(string arg0, string[] arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseResponse", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class PurchaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public PurchaseResponse() {
        }
        
        public PurchaseResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomer", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCustomerRequest() {
        }
        
        public getCustomerRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerResponse", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getCustomerResponse() {
        }
        
        public getCustomerResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductDetail", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getProductDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getProductDetailRequest() {
        }
        
        public getProductDetailRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductDetailResponse", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getProductDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getProductDetailResponse() {
        }
        
        public getProductDetailResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductIds", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getProductIdsRequest {
        
        public getProductIdsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductIdsResponse", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getProductIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getProductIdsResponse() {
        }
        
        public getProductIdsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerOrders", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getCustomerOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCustomerOrdersRequest() {
        }
        
        public getCustomerOrdersRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCustomerOrdersResponse", WrapperNamespace="http://jwsorderprocessing/", IsWrapped=true)]
    public partial class getCustomerOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://jwsorderprocessing/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getCustomerOrdersResponse() {
        }
        
        public getCustomerOrdersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderProcessingServiceChannel : TestClient.jwsopservice.OrderProcessingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderProcessingServiceClient : System.ServiceModel.ClientBase<TestClient.jwsopservice.OrderProcessingService>, TestClient.jwsopservice.OrderProcessingService {
        
        public OrderProcessingServiceClient() {
        }
        
        public OrderProcessingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderProcessingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderProcessingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.jwsopservice.getOrderDetailsResponse TestClient.jwsopservice.OrderProcessingService.getOrderDetails(TestClient.jwsopservice.getOrderDetailsRequest request) {
            return base.Channel.getOrderDetails(request);
        }
        
        public string[] getOrderDetails(string arg0) {
            TestClient.jwsopservice.getOrderDetailsRequest inValue = new TestClient.jwsopservice.getOrderDetailsRequest();
            inValue.arg0 = arg0;
            TestClient.jwsopservice.getOrderDetailsResponse retVal = ((TestClient.jwsopservice.OrderProcessingService)(this)).getOrderDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getOrderDetailsResponse> TestClient.jwsopservice.OrderProcessingService.getOrderDetailsAsync(TestClient.jwsopservice.getOrderDetailsRequest request) {
            return base.Channel.getOrderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestClient.jwsopservice.getOrderDetailsResponse> getOrderDetailsAsync(string arg0) {
            TestClient.jwsopservice.getOrderDetailsRequest inValue = new TestClient.jwsopservice.getOrderDetailsRequest();
            inValue.arg0 = arg0;
            return ((TestClient.jwsopservice.OrderProcessingService)(this)).getOrderDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.jwsopservice.PurchaseResponse TestClient.jwsopservice.OrderProcessingService.Purchase(TestClient.jwsopservice.PurchaseRequest request) {
            return base.Channel.Purchase(request);
        }
        
        public int Purchase(string arg0, string[] arg1) {
            TestClient.jwsopservice.PurchaseRequest inValue = new TestClient.jwsopservice.PurchaseRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            TestClient.jwsopservice.PurchaseResponse retVal = ((TestClient.jwsopservice.OrderProcessingService)(this)).Purchase(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestClient.jwsopservice.PurchaseResponse> TestClient.jwsopservice.OrderProcessingService.PurchaseAsync(TestClient.jwsopservice.PurchaseRequest request) {
            return base.Channel.PurchaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestClient.jwsopservice.PurchaseResponse> PurchaseAsync(string arg0, string[] arg1) {
            TestClient.jwsopservice.PurchaseRequest inValue = new TestClient.jwsopservice.PurchaseRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((TestClient.jwsopservice.OrderProcessingService)(this)).PurchaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.jwsopservice.getCustomerResponse TestClient.jwsopservice.OrderProcessingService.getCustomer(TestClient.jwsopservice.getCustomerRequest request) {
            return base.Channel.getCustomer(request);
        }
        
        public string getCustomer(string arg0) {
            TestClient.jwsopservice.getCustomerRequest inValue = new TestClient.jwsopservice.getCustomerRequest();
            inValue.arg0 = arg0;
            TestClient.jwsopservice.getCustomerResponse retVal = ((TestClient.jwsopservice.OrderProcessingService)(this)).getCustomer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getCustomerResponse> TestClient.jwsopservice.OrderProcessingService.getCustomerAsync(TestClient.jwsopservice.getCustomerRequest request) {
            return base.Channel.getCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestClient.jwsopservice.getCustomerResponse> getCustomerAsync(string arg0) {
            TestClient.jwsopservice.getCustomerRequest inValue = new TestClient.jwsopservice.getCustomerRequest();
            inValue.arg0 = arg0;
            return ((TestClient.jwsopservice.OrderProcessingService)(this)).getCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.jwsopservice.getProductDetailResponse TestClient.jwsopservice.OrderProcessingService.getProductDetail(TestClient.jwsopservice.getProductDetailRequest request) {
            return base.Channel.getProductDetail(request);
        }
        
        public string getProductDetail(string arg0) {
            TestClient.jwsopservice.getProductDetailRequest inValue = new TestClient.jwsopservice.getProductDetailRequest();
            inValue.arg0 = arg0;
            TestClient.jwsopservice.getProductDetailResponse retVal = ((TestClient.jwsopservice.OrderProcessingService)(this)).getProductDetail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getProductDetailResponse> TestClient.jwsopservice.OrderProcessingService.getProductDetailAsync(TestClient.jwsopservice.getProductDetailRequest request) {
            return base.Channel.getProductDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestClient.jwsopservice.getProductDetailResponse> getProductDetailAsync(string arg0) {
            TestClient.jwsopservice.getProductDetailRequest inValue = new TestClient.jwsopservice.getProductDetailRequest();
            inValue.arg0 = arg0;
            return ((TestClient.jwsopservice.OrderProcessingService)(this)).getProductDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.jwsopservice.getProductIdsResponse TestClient.jwsopservice.OrderProcessingService.getProductIds(TestClient.jwsopservice.getProductIdsRequest request) {
            return base.Channel.getProductIds(request);
        }
        
        public string[] getProductIds() {
            TestClient.jwsopservice.getProductIdsRequest inValue = new TestClient.jwsopservice.getProductIdsRequest();
            TestClient.jwsopservice.getProductIdsResponse retVal = ((TestClient.jwsopservice.OrderProcessingService)(this)).getProductIds(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getProductIdsResponse> TestClient.jwsopservice.OrderProcessingService.getProductIdsAsync(TestClient.jwsopservice.getProductIdsRequest request) {
            return base.Channel.getProductIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestClient.jwsopservice.getProductIdsResponse> getProductIdsAsync() {
            TestClient.jwsopservice.getProductIdsRequest inValue = new TestClient.jwsopservice.getProductIdsRequest();
            return ((TestClient.jwsopservice.OrderProcessingService)(this)).getProductIdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestClient.jwsopservice.getCustomerOrdersResponse TestClient.jwsopservice.OrderProcessingService.getCustomerOrders(TestClient.jwsopservice.getCustomerOrdersRequest request) {
            return base.Channel.getCustomerOrders(request);
        }
        
        public string[] getCustomerOrders(string arg0) {
            TestClient.jwsopservice.getCustomerOrdersRequest inValue = new TestClient.jwsopservice.getCustomerOrdersRequest();
            inValue.arg0 = arg0;
            TestClient.jwsopservice.getCustomerOrdersResponse retVal = ((TestClient.jwsopservice.OrderProcessingService)(this)).getCustomerOrders(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestClient.jwsopservice.getCustomerOrdersResponse> TestClient.jwsopservice.OrderProcessingService.getCustomerOrdersAsync(TestClient.jwsopservice.getCustomerOrdersRequest request) {
            return base.Channel.getCustomerOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestClient.jwsopservice.getCustomerOrdersResponse> getCustomerOrdersAsync(string arg0) {
            TestClient.jwsopservice.getCustomerOrdersRequest inValue = new TestClient.jwsopservice.getCustomerOrdersRequest();
            inValue.arg0 = arg0;
            return ((TestClient.jwsopservice.OrderProcessingService)(this)).getCustomerOrdersAsync(inValue);
        }
    }
}
